spring.application.name=gestionale

# Configurazione porta server springboot
server.port=8081

# Driver DB (scegli il driver corretto per il tuo DB)
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

# Dialect Hibernate
spring.jpa.database-platform=org.hibernate.dialect.MariaDBDialect

# Dati di connessione al database
spring.datasource.url=jdbc:mariadb://127.0.0.1:3306/Barberflow
spring.datasource.username=root
spring.datasource.password=

# Comportamento Hibernate
spring.jpa.hibernate.ddl-auto=create-drop

# Mostra query SQL in console
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# JWT configuration
app.jwt.secret=${JWT_SECRET:una_chiave_lunga_e_sicura_change_this_to_longer_value_12345689}
app.jwt.expiration-ms=${JWT_EXPIRATION_MS:86400000}
